language: go
go:
  - 1.6
  - 1.7

install:
  - go get github.com/gonum/matrix/mat64
  - go get github.com/stretchr/testify/assert

before_script:
  - go get github.com/golang/lint

script:
  - make test
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)
